apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-loan
spec:
  selector:
    matchLabels:
      app: fintech-loan
  template:
    metadata:
      labels:
        app: fintech-loan
    spec:
      containers:
        - name: fintech-loan
          image: fintech-loan
          ports:
            - containerPort: 8080